### ISSUE TITLE
Change parameter t by its components

### ISSUE THREAD

**Issue by bpulidob** [bpulidob/ehymet#6]
Functions ind and EHyClus (check if this happens for more functions) require parameter `t`, with `t <- seq(ll, ul, length = p)`, where ll = lower limit and ul = upper limit. 

To do: change t parameter by ll, ul and p, and generate t (or grid) when necessary. For example, ind function needs t, but EHyClus only needs t as parameter of ind, so t is not required. 

See functions for model generation in `simulation_models.R` where t is generated inside each function.

**Comment by nachodieez** [comment]
I think the length (`p`) can always be obtained as `dim(curves)[2]` both for the unidimensional and multidimensional case, so we can omit that parameter.

Also, I think that `ll` and `up` are a bit terse names to represent what the parameters do. Calling them `lower_limit` and `upper_limit` wouldn't help much either because they don't refer directly to the grid. 

Maybe call them `grid_ll` and `grid_ul`? And document well what the grid is.
